server:
  port: 8080
  servlet:
    context-path: /sais
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m

spring:
  application:
    name: Sosyal Yardım Bilgi Sistemi
  
  banner:
    charset: UTF-8
  
  messages:
    encoding: UTF-8
  
  # Multipart File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      file-size-threshold: 2KB
    
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orclpdb
    username: SAIS
    password: Sais123!
    driver-class-name: oracle.jdbc.OracleDriver
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: false
        show_sql: false
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
        use_sql_comments: false
        use_jdbc_metadata_defaults: false
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: false
  
  sql:
    init:
      mode: never
      
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


joinfaces:
  faces:
    project-stage: Development
    facelets:
      skip-comments: true
      refresh-period: 0
    state-saving-method: server
    default-charset: UTF-8
    validate-empty-fields: false
    partial-state-saving: true
    view-expired-exception-handling: true
  primefaces:
    theme: saga
    font-awesome: true
    ajax-push: false
    client-side-validation: true
  mojarra:
    enable-standalone: true
    

file:
  storage:
    upload-dir: uploads
    muracaat-dir: muracaat
    allowed-types: pdf,doc,docx,jpg,jpeg,png,gif,xls,xlsx,txt
    max-file-size: 10485760  # 10MB in bytes

logging:
  level:
    com.sais: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework: INFO
    org.primefaces: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  charset:
    console: UTF-8
